[build]
  command="ng build"
  publish="dist/angular-quickstart"
  functions="functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = '/api/*'
  force = true
  to = '/.netlify/functions/api/:splat'
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false

[functions]
  directory = "functions"
